feat: 30 Create a npm script to generate a new rule boilerplate
hokla-org/eslint-plugin-custom-rules pull request #46
Opened 2023-08-21 15:30 UTC by bilmans

Adds a new command "yarn generate" that generate :
- A rule file boilerplate
- A test file boilerplate
- A doc file boilerplate

🎯 *Issue* https://github.com/hokla-org/eslint-plugin-custom-rules/issues/30 

## 📣 When merging !

Please inform everyone to upgrade the hokla eslint plugin to benefit from your piece !
https://hokla.slack.com/archives/C02CZUN4QUW
Tell them to run `yarn upgrade @hokla/eslint-plugin-custom-rules` or `npm update @hokla/eslint-plugin-custom-rules`

2023-08-21 15:48 UTC, bilmans commented
Does the script needs to be executable by other devs for it to work (using the `chmod` command) ?

2023-08-23 16:16 UTC, Ludo171 requested changes
Très cool ! 

Autres retours de nommage : 
- Le nommage utiliser plutôt du camelCase que du snakeCase. `generateNewRule` `rule.boilerplate.ts` `ruleTests.boilerplate.ts`

2023-08-23 16:16 UTC, Ludo171 commented on generate/generate-boilerplate.ts
> +const path = require('path');
Il doit y avoir moyen d'accepter les imports classiques 
import * as fs from 'fs'; ...

2023-08-23 16:16 UTC, Ludo171 commented on package.json
> +    "generate": "node generate/generate-boilerplate.ts && yarn build && yarn create:eslint-docs"
On peut nommer le script plus clairement : 
`rule:generate`

2023-08-24 09:10 UTC, merged